# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neural_input_rcpp <- function(x, from, to, resolution) {
    .Call(`_fmrihrf_neural_input_rcpp`, x, from, to, resolution)
}

evaluate_regressor_convolution <- function(grid, onsets, durations, amplitudes, hrf_values, hrf_span, start, end, precision) {
    .Call(`_fmrihrf_evaluate_regressor_convolution`, grid, onsets, durations, amplitudes, hrf_values, hrf_span, start, end, precision)
}

evaluate_regressor_fast <- function(grid, onsets, durations, amplitudes, hrfFine, dt, span) {
    .Call(`_fmrihrf_evaluate_regressor_fast`, grid, onsets, durations, amplitudes, hrfFine, dt, span)
}

evaluate_regressor_cpp <- function(grid, onsets, durations, amplitudes, hrf_matrix, hrf_span, precision, method = "fft") {
    .Call(`_fmrihrf_evaluate_regressor_cpp`, grid, onsets, durations, amplitudes, hrf_matrix, hrf_span, precision, method)
}

